### ISSUE TITLE
'PhasedRead' object has no attribute 'is_phased' error

### ISSUE THREAD

**Issue by camelest** [Boyle-Lab/HaplotagLR#20]
Hi, thank you so much for a wonderful tool!

I was trying to use HaplotagLR on a heterozygous mouse dataset and getting the error below. The test data were processed with no errors. Do you have any ideas on what could be fixed? Is it some format problem in the bam file? (The bam file was aligned by `pbmm2`.)

Thank you so much for your help.

```
HaplotagLR --version
1.1.5

HaplotagLR haplotag -v phased.vcf.gz -I aligned.bam -o haplotagLR -r GRCm38.primary_assembly.genome.fa -O full

Haplotagging reads...
Processing alignments for sample 0 (C57BL_6NJ_PWK_PhJ)...
Traceback (most recent call last):
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env/bin/HaplotagLR", line 10, in <module>
    sys.exit(main())
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env/lib/python3.8/site-packages/HaplotagLR/cli.py", line 1302, in main
    args: argparse.Namespace = getArgs()
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env/lib/python3.8/site-packages/HaplotagLR/cli.py", line 1296, in getArgs
    args.func(args)
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env/lib/python3.8/site-packages/HaplotagLR/cli.py", line 142, in haplotag
    write_bam_output(phased_read, output_streams, args)
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env/lib/python3.8/site-packages/HaplotagLR/cli.py", line 256, in write_bam_output
    write_full_bam_output(phased_read,
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env/lib/python3.8/site-packages/HaplotagLR/cli.py", line 301, in write_full_bam_output
    if phased_read.is_phased:
AttributeError: 'PhasedRead' object has no attribute 'is_phased'
```

**Comment by adadiehl** [comment]
Thanks for bringing this to our attention! I believe I've identified the problem and have released a new patch. Please let me know if this solves your issue.

**Comment by camelest** [comment]
Thank you so much for your prompt response.

Now the message changed a bit but still with errors.

```
HaplotagLR --version
1.1.8

Haplotagging reads...
Processing alignments for sample 0 (C57BL_6NJ_PWK_PhJ)...
Traceback (most recent call last):
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env2/bin/HaplotagLR", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env2/lib/python3.12/site-packages/HaplotagLR/cli.py", line 1302, in main
    args: argparse.Namespace = getArgs()
                               ^^^^^^^^^
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env2/lib/python3.12/site-packages/HaplotagLR/cli.py", line 1296, in getArgs
    args.func(args)
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env2/lib/python3.12/site-packages/HaplotagLR/cli.py", line 142, in haplotag
    write_bam_output(phased_read, output_streams, args)
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env2/lib/python3.12/site-packages/HaplotagLR/cli.py", line 256, in write_bam_output
    write_full_bam_output(phased_read,
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env2/lib/python3.12/site-packages/HaplotagLR/cli.py", line 310, in write_full_bam_output
    elif phased_read.is_Unphased:
         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PhasedRead' object has no attribute 'is_Unphased'. Did you mean: 'is_Untagged'?
```

**Comment by adadiehl** [comment]
Okay, I've corrected the issue and checked to see if any similar problems may still exist that use the old variable names. Version 1.1.9 should be available through pip shortly and bioconda within the next day or so. Hopefully this does it for you. Let me know either way. Thanks!

**Comment by camelest** [comment]
Hi, thank you so much again.

I think now it proceeded a bit more but I'm getting the message below.

```
Haplotagging reads...
Processing alignments for sample 0 (C57BL_6NJ_PWK_PhJ)...
Traceback (most recent call last):
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/bin/HaplotagLR", line 10, in <module>
    sys.exit(main())
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 1302, in main
    args: argparse.Namespace = getArgs()
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 1296, in getArgs
    args.func(args)
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 109, in haplotag
    phased_read = PhasedRead(alignment,
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/PhasedRead.py", line 310, in __init__
    self.tag_read(
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/PhasedRead.py", line 412, in tag_read
    _PhaseSet_max = self._select_best_haplotag(
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/PhasedRead.py", line 460, in _select_best_haplotag
    _PhaseSet.solve_phase(
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/PhaseSet.py", line 612, in solve_phase
    self.per_base_mismatch_rate = self.aligned_segment.get_tag(tag = 'de')
  File "pysam/libcalignedsegment.pyx", line 2399, in pysam.libcalignedsegment.AlignedSegment.get_tag
  File "pysam/libcalignedsegment.pyx", line 2438, in pysam.libcalignedsegment.AlignedSegment.get_tag
KeyError: "tag 'de' not present"
```

By the way, though v1.1.5, 1.1.8, 1.1.9, I needed to modify line 848 in InputData.py as below to have it work till the point I mentioned above. (Sorry I should have let you know earlier)

From
```
for PG_header in self.sample_to_PG_header[sample]:
                            if PG_tag['PN'] == PG_header['PN'] and PG_tag['ID'] == PG_header['ID']:
                                new_PG_tag = False
```
to
```
for PG_header in self.sample_to_PG_header[sample]:
 # 2024/8/14 modified
                            if 'PN' in PG_tag and 'PN' in PG_header and 'ID' in PG_tag and 'ID' in PG_header:
                                if PG_tag['PN'] == PG_header['PN'] and PG_tag['ID'] == PG_header['ID']:
                                    new_PG_tag = False
```

Without the modification I would get
```
Traceback (most recent call last):
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/bin/HaplotagLR", line 10, in <module>
    sys.exit(main())
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 1302, in main
    args: argparse.Namespace = getArgs()
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 1296, in getArgs
    args.func(args)
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 69, in haplotag
    input_data.add_reads(args.long_read_inputs,
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/InputData.py", line 708, in add_reads
    self._sample_to_PG_dict(sam_file_path = sorted_bam_file_path[0])
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/InputData.py", line 848, in _sample_to_PG_dict
    if PG_tag['PN'] == PG_header['PN'] and PG_tag['ID'] == PG_header['ID']:
KeyError: 'PN'
```

I checked the PG tag in my bam file, which looked like this:
```
samtools view aligned.bam -H | grep "PG"

@PG     ID:isoseq groupdedup    VN:4.0.0 (commit v4.0.0)        CL:groupdedup fltnc.corrected_default.sorted.dedup_keepall.bam --log-level INFO --keep-non-real-cells
@PG     ID:pbmm2        PN:pbmm2        VN:1.13.0 (commit v1.13.0-2-gbcd99f5)   CL:pbmm2 align --preset ISOSEQ --sort fltnc.corrected_default.sorted.dedup_keepall.bam reference.fa fltnc.corrected_default.sorted.dedup_tissue_gem_keepall.mapped.bam --log-level INFO
@PG     ID:samtools     PN:samtools     PP:pbmm2        VN:1.15.1       CL:samtools view -H aligned.bam
```

Hopefully these information would help. Thank you again for your kind support.

**Comment by adadiehl** [comment]
Thank you for bringing the PG header issue to my attention. I have addressed that and made a new commit, but waiting on a new release until I can address the 'de' tag issue also. As far as that goes, the 'de' tag reports the average per-base mismatch rate in the alignment, and is added by minimap2. However, I have discovered that the 'de' tag is nonstandard, according to BAM format documentation, and so may not be added by aligners other than minimap2. Guessing you are in that boat, since your BAM records don't seem to contain the 'de' tag. Let me know and I can look into a possible solution.

**Comment by camelest** [comment]
Thank you so much for your response. 
I see, I will try minimap2 instead of pbmm2 then and get back to you.

Thank you again for your kind help.

**Comment by camelest** [comment]
Hi, I'm so sorry for taking long time. I remapped our data by minimap2 and tried with haplotagLR v1.1.9. 
The 'de' tag error disappeared but I still get the error below.

```
Haplotagging reads...
Processing alignments for sample 0 (C57BL_6NJ_PWK_PhJ)...
Traceback (most recent call last):
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/bin/HaplotagLR", line 10, in <module>
    sys.exit(main())
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 1302, in main
    args: argparse.Namespace = getArgs()
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 1296, in getArgs
    args.func(args)
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 142, in haplotag
    write_bam_output(phased_read, output_streams, args)
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 256, in write_bam_output
    write_full_bam_output(phased_read,
  File "/local/home/ubuntu/anaconda3/envs/HaplotagLR_env3/lib/python3.9/site-packages/HaplotagLR/cli.py", line 303, in write_full_bam_output
    if phased_read.phase == 1:
AttributeError: 'PhasedRead' object has no attribute 'phase'
```

Thank you so much for your help.
